# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ed6ecb283b91b670bbce93e57030351190cbe77a741aca64d8cfe983036ce50e812ec89ce8377e920bee8f7466dd9267abf59b92a3cd2fa8e94133ea7329b77

test:
  secret_key_base: 4328b52bae123c1274395c2fd8ce82a2454161cedbaac2c6bb9b60574d053855a06c37552c6dcff401c8f4f9caacd5611148a988ee4c46fe48cc7e5f5a67fb1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
